# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install python-numpy python3-numpy
  - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors numpy
  
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test